include_recipe "utilite::default"

package "curl"
package "wget"
package "mount"
package "dmsetup"
package "parted"
package "kpartx"
package "qemu-utils"
package "default-jre-headless"
package "pbzip2"
package "git"
package "ruby1.9.1"
package "rubygems"
package "ruby1.9.1-dev"
