include_recipe "utilite::default"

package "curl"
package "wget"
package "mount"
package "dmsetup"
package "parted"
package "kpartx"
package "qemu-utils"
package "default-jre-headless"
package "pbzip2"
